/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradlecalc;

import org.apache.commons.math3.primes.Primes;

public class App {
    
    private static float operand1;

    private static float operand2;
    
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        if (args.length != 2) {

        System.out.println("\nSintaxi incorrecta. Necessite dos números.");

        System.exit(-1);

    }


    operand1=Float.parseFloat(args[0]);

    operand2=Float.parseFloat(args[1]);


    Calculadora myCalc=new Calculadora();


    System.out.println("La suma entre "+operand1+" i "+operand2+" és "+myCalc.suma(operand1, operand2));

    System.out.println("La resta entre "+operand1+" i "+operand2+"és "+myCalc.resta(operand1, operand2));

    System.out.println("La multiplicació entre "+operand1+" i "+operand2+" és "+myCalc.multiplica(operand1, operand2));

    System.out.println("La divisió entre "+operand1+" i "+operand2+" és "+myCalc.divideix(operand1, operand2));

    System.out.println("Última operació realitzada: "+myCalc.getLastOp()+"; Últim resultat: "+myCalc.getLastResult());
    
    // AFEGIM COMPROVACIÓ SI OPERAND 1 ES PRIM O NO
    int op1=(int)operand1;
    boolean resultat=Primes.isPrime(op1);
    if(resultat==true){
        System.out.println("El numero "+operand1+" es prim");
    }else{
        System.out.println("El numero "+operand1+" no es prim");
    }
    
    // AFEGIM L'OPCIÓ QUE ENS DIU EL PROXIM NUMERO PRIM
    int proxPrim=Primes.nextPrime(op1+1);
        System.out.println("El proxim numero prim es "+proxPrim);
    
    }
}
